Fix AttributeError in console
Issue:
When the console is active and keys are pressed, line 582 causes
`AttributeError: 'pygame.event.Event' object has no attribute 'str'`

Fix:
Replace event.str with event.unicode